"""Modernized Python 3.14 wrapper for sp_atualizar_status_contas_inativas.

Generated by the hybrid SQL-to-Python modernization pipeline.
The original PL/pgSQL is kept as SQL text because this MVP prioritizes
semantic preservation and auditable translation decisions over full SQL rewriting.
"""

from __future__ import annotations

from typing import Any


SOURCE_SQL = """\
CREATE OR REPLACE PROCEDURE sp_atualizar_status_contas_inativas(
    IN p_dias INT,
    OUT p_afetadas INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_dias IS NULL OR p_dias <= 0 THEN
        RAISE EXCEPTION 'Parametro p_dias deve ser positivo, recebido: %', p_dias;
    END IF;

    UPDATE contas c
       SET status = 'INATIVA'
     WHERE c.status = 'ATIVA'
       AND NOT EXISTS (
            SELECT 1
              FROM transacoes t
             WHERE (t.conta_origem_id = c.id OR t.conta_destino_id = c.id)
               AND t.data_transacao >= NOW() - (p_dias || ' days')::INTERVAL
       );

    GET DIAGNOSTICS p_afetadas = ROW_COUNT;

    INSERT INTO log_auditoria (entidade, acao, detalhes)
    VALUES (
        'contas',
        'INATIVACAO_LOTE',
        jsonb_build_object('dias', p_dias, 'afetadas', p_afetadas)
    );
END;
$$;
"""


def sp_atualizar_status_contas_inativas(
    connection: object,
    p_dias: object,
) -> Any:
    """Execute the modernized routine using an existing DB connection.

    The caller owns transaction boundaries unless the delegated SQL contains
    database-side transaction behavior. Inputs mirror the original routine
    parameters where they could be detected.
    """
    if connection is None:
        raise ValueError("connection is required")

    # Keep the executable database logic explicit and auditable.
    with connection.cursor() as cursor:
        cursor.execute(SOURCE_SQL)
        if cursor.description:
            return cursor.fetchall()
        return {"rowcount": cursor.rowcount}
