"""Modernized Python 3.14 wrapper for fn_saldo_cliente.

Generated by the hybrid SQL-to-Python modernization pipeline.
The original PL/pgSQL is kept as SQL text because this MVP prioritizes
semantic preservation and auditable translation decisions over full SQL rewriting.
"""

from __future__ import annotations

from typing import Any


SOURCE_SQL = """\
CREATE OR REPLACE FUNCTION fn_saldo_cliente(p_cliente_id BIGINT)
RETURNS NUMERIC(18,2)
LANGUAGE plpgsql
AS $$
DECLARE
    v_total NUMERIC(18,2);
BEGIN
    SELECT COALESCE(SUM(saldo), 0)
      INTO v_total
      FROM contas
     WHERE cliente_id = p_cliente_id
       AND status = 'ATIVA';

    RETURN v_total;
END;
$$;
"""


def fn_saldo_cliente(
    connection: object,
    p_cliente_id: object,
) -> Any:
    """Execute the modernized routine using an existing DB connection.

    The caller owns transaction boundaries unless the delegated SQL contains
    database-side transaction behavior. Inputs mirror the original routine
    parameters where they could be detected.
    """
    if connection is None:
        raise ValueError("connection is required")

    # Keep the executable database logic explicit and auditable.
    with connection.cursor() as cursor:
        cursor.execute(SOURCE_SQL)
        if cursor.description:
            return cursor.fetchall()
        return {"rowcount": cursor.rowcount}
