"""Modernized Python 3.14 wrapper for sp_processar_lote_taxas.

Generated by the hybrid SQL-to-Python modernization pipeline.
The original PL/pgSQL is kept as SQL text because this MVP prioritizes
semantic preservation and auditable translation decisions over full SQL rewriting.
"""

from __future__ import annotations

from typing import Any


SOURCE_SQL = """\
CREATE OR REPLACE PROCEDURE sp_processar_lote_taxas(IN p_data_referencia DATE)
LANGUAGE plpgsql
AS $$
DECLARE
    cur_transacoes CURSOR FOR
        SELECT id, conta_origem_id, tipo, valor
          FROM transacoes
         WHERE DATE(data_transacao) = p_data_referencia
           AND status = 'EFETIVADA'
           AND tipo <> 'TARIFA';

    v_id BIGINT;
    v_origem BIGINT;
    v_tipo VARCHAR(20);
    v_valor NUMERIC(18,2);
    v_taxa NUMERIC(18,2);
    v_percentual NUMERIC(7,4);
    v_minimo NUMERIC(18,2);
    v_total_taxas NUMERIC(18,2) := 0;
    v_count INT := 0;
BEGIN
    OPEN cur_transacoes;

    LOOP
        FETCH cur_transacoes INTO v_id, v_origem, v_tipo, v_valor;
        EXIT WHEN NOT FOUND;

        SELECT percentual, valor_minimo
          INTO v_percentual, v_minimo
          FROM taxas
         WHERE tipo_operacao = v_tipo
           AND vigente_de <= p_data_referencia
           AND (vigente_ate IS NULL OR vigente_ate >= p_data_referencia)
         ORDER BY vigente_de DESC
         LIMIT 1;

        IF v_percentual IS NULL THEN
            CONTINUE;
        END IF;

        v_taxa := GREATEST(v_valor * v_percentual / 100.0, v_minimo);

        CASE v_tipo
            WHEN 'TRANSFERENCIA' THEN v_taxa := v_taxa;
            WHEN 'SAQUE' THEN v_taxa := v_taxa * 1.10;
            ELSE v_taxa := v_taxa * 0.90;
        END CASE;

        IF v_origem IS NOT NULL THEN
            UPDATE contas SET saldo = saldo - v_taxa WHERE id = v_origem;
            INSERT INTO transacoes (conta_origem_id, tipo, valor, status)
            VALUES (v_origem, 'TARIFA', v_taxa, 'EFETIVADA');
            INSERT INTO log_auditoria (entidade, entidade_id, acao, detalhes)
            VALUES ('transacoes', v_id, 'TARIFA_APLICADA', jsonb_build_object('taxa', v_taxa));
            v_total_taxas := v_total_taxas + v_taxa;
            v_count := v_count + 1;
        END IF;
    END LOOP;

    CLOSE cur_transacoes;
END;
$$;
"""


def sp_processar_lote_taxas(
    connection: object,
    p_data_referencia: object,
) -> Any:
    """Execute the modernized routine using an existing DB connection.

    The caller owns transaction boundaries unless the delegated SQL contains
    database-side transaction behavior. Inputs mirror the original routine
    parameters where they could be detected.
    """
    if connection is None:
        raise ValueError("connection is required")

    # Keep the executable database logic explicit and auditable.
    with connection.cursor() as cursor:
        cursor.execute(SOURCE_SQL)
        if cursor.description:
            return cursor.fetchall()
        return {"rowcount": cursor.rowcount}
