
from app.graph.state import ModernizationState
from app.integrations.llm import (
    build_generation_context,
    build_generation_prompt,
    extract_python_code,
    get_ai_provider,
    prompt_summary,
)


def _routine_name(state: ModernizationState) -> str:
    findings = state.get("semantic_findings", {})
    routine = findings.get("routine", {}) if isinstance(findings, dict) else {}
    return str(routine.get("name") or "modernized_procedure")


def _parameter_names(state: ModernizationState) -> list[str]:
    findings = state.get("semantic_findings", {})
    params = findings.get("parameters", []) if isinstance(findings, dict) else []
    names = [str(param["name"]) for param in params if param.get("direction", "IN") != "OUT"]
    return names or ["connection"]


def _signature_params(state: ModernizationState) -> str:
    names = _parameter_names(state)
    if "connection" not in names:
        names = ["connection", *names]
    return "\n".join(f"    {name}: object," for name in names)


def _sql_constant(source: str) -> str:
    escaped = source.strip().replace('"""', r"\"\"\"")
    return f'"""\\\n{escaped}\n"""'


def _deterministic_generate(state: ModernizationState) -> tuple[str, list[str], str]:
    source = state.get("source_code", "")
    findings = state.get("semantic_findings", {})
    routine_name = _routine_name(state)
    params = _signature_params(state)

    decisions: list[str] = [
        "Generated code uses a Python wrapper around explicit SQL delegation.",
        (
            "This preserves database semantics for PL/pgSQL constructs "
            "that are risky to rewrite quickly."
        ),
        (
            "The prompt/context boundary is represented by parsed_representation "
            "and semantic_findings."
        ),
    ]
    if findings.get("cursor"):
        decisions.append(
            "Cursor-heavy logic is not expanded into Python loops to avoid accidental N+1 behavior."
        )
    if findings.get("recursive_cte"):
        decisions.append("Recursive CTE logic remains delegated to PostgreSQL.")
    if findings.get("exception_block"):
        decisions.append(
            "Database exception behavior is surfaced as Python exceptions from the DB driver."
        )

    body = f'''"""Modernized Python 3.14 wrapper for {routine_name}.

Generated by the hybrid SQL-to-Python modernization pipeline.
The original PL/pgSQL is kept as SQL text because this MVP prioritizes
semantic preservation and auditable translation decisions over full SQL rewriting.
"""

from __future__ import annotations

from typing import Any


SOURCE_SQL = {_sql_constant(source)}


def {routine_name}(
{params}
) -> Any:
    """Execute the modernized routine using an existing DB connection.

    The caller owns transaction boundaries unless the delegated SQL contains
    database-side transaction behavior. Inputs mirror the original routine
    parameters where they could be detected.
    """
    if connection is None:
        raise ValueError("connection is required")

    # Keep the executable database logic explicit and auditable.
    with connection.cursor() as cursor:
        cursor.execute(SOURCE_SQL)
        if cursor.description:
            return cursor.fetchall()
        return {{"rowcount": cursor.rowcount}}
'''

    return body, decisions, routine_name


def _should_prefer_ai(state: ModernizationState) -> bool:
    confidence = state.get("confidence", {})
    parsing = float(confidence.get("parsing", 1.0))
    semantic = float(confidence.get("semantic_analysis", 1.0))
    return parsing < 0.8 or semantic < 0.8 or bool(state.get("errors"))


def generate_python(state: ModernizationState) -> ModernizationState:
    report = state.setdefault("report", {"stages": {}, "decisions": [], "risks": []})
    context = build_generation_context(state)
    provider = get_ai_provider()
    prompt = build_generation_prompt(state)
    prefer_ai = _should_prefer_ai(state)
    ai_result = provider.generate(prompt)

    if ai_result.available and ai_result.text.strip():
        code = extract_python_code(ai_result.text)
        state["generated_code"] = code
        state["generation_strategy"] = "ai"
        state["ai_context"] = prompt_summary(prompt)
        state["ai_usage"] = ai_result.usage
        report["stages"]["generation"] = {
            "status": "ok",
            "strategy": "ai",
            "provider": ai_result.provider,
            "model": ai_result.model,
            "prompt": prompt_summary(prompt),
            "usage": ai_result.usage,
            "preferred_due_to_low_confidence": prefer_ai,
        }
        report["decisions"] = list(
            dict.fromkeys(
                [
                    *report.get("decisions", []),
                    "AI generation used structured parser and semantic-analysis context.",
                ]
            )
        )
        return state

    body, decisions, routine_name = _deterministic_generate(state)
    strategy = "deterministic_fallback" if prefer_ai or ai_result.error else "deterministic"
    state["generated_code"] = body
    state["generation_strategy"] = strategy
    report["stages"]["generation"] = {
        "status": "ok",
        "routine_name": routine_name,
        "strategy": strategy,
        "ai_provider": ai_result.provider,
        "ai_model": ai_result.model,
        "ai_unavailable_reason": ai_result.error,
        "preferred_ai_due_to_low_confidence": prefer_ai,
        "context_keys": sorted(context.keys()),
        "decisions": decisions,
        "prompt": prompt_summary(prompt),
    }
    report["decisions"] = list(dict.fromkeys([*report.get("decisions", []), *decisions]))
    return state
